apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "fullname" . }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ template "fullname" . }}
  ports:
  - name: {{ template "fullname" . }}
    port: 5000
